### ISSUE TITLE
AudioInput does not close properly

### ISSUE THREAD

**Issue by Cheesemaster64** [ddf/Minim#32] opened 2015-02-08 11:29 UTC
The following code:

_minim = new Minim(this);
_in = _minim.getLineIn(Minim.STEREO, 512);
_in.close();
_in = _minim.getLineIn(Minim.STEREO, 512);

results in this error:

"Error acquiring TargetDataLine: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported"

I think this may be a bug in JavaAudio, because I am trying to use the Voce library and the same exact error occurs after trying to close and then reopen an input stream.

**Comment by ddf** [comment] 2015-02-10 03:57
I just tried this on my Mac and was unable to reproduce it. What is your OS, Java version, and Processing version?

**Comment by ddf** [comment] 2015-02-10 04:01
Also, this is probably fixed by this: https://github.com/ddf/Minim/issues/28

**Comment by Cheesemaster64** [comment] 2015-02-10 04:04
Thanks for the response.

Windows 8 64-bit
Processing 2.2.1 & 3.0a5
Java 1.7.0.71

I will install the latest Java and see if this issue is solved.

2015年2月10日火曜日、Damien Di Fede<notifications@github.com>さんは書きました:

**Comment by ddf** [comment] 2015-02-10 04:08
Before installing the latest Java you might try replacing your Minim jar files with the lastest from the repository.

**Comment by Cheesemaster64** [comment] 2015-02-10 04:11
Unfortunately I tried this already and it did not work.


On Tue, Feb 10, 2015 at 1:08 PM, Damien Di Fede <notifications@github.com>
wrote:

> Before installing the latest Java you might try replacing your Minim jar
> files with the lastest from the repository.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ddf/Minim/issues/32#issuecomment-73641318>.
>



-- 
Corey Bunnell

**Comment by ddf** [comment] 2015-02-10 04:15
Ah ok, good to know.

**Comment by ddf** [comment] 2015-02-10 04:16
My Mac is on Java 1.7.0_45, fwiw.

**Comment by Cheesemaster64** [comment] 2015-02-10 04:22
I have updated to java 1.8, still have the same error.

As I have said before, the Voce library has the same problem, so I am
pretty sure it is not being caused by Minim.

Thanks for you time. Please let me know if you have any ideas what could be
causing this.

On Tue, Feb 10, 2015 at 1:16 PM, Damien Di Fede <notifications@github.com>
wrote:

> My Mac is on Java 1.7.0_45, fwiw.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ddf/Minim/issues/32#issuecomment-73641813>.
>



-- 
Corey Bunnell

**Comment by ddf** [comment] 2015-02-10 04:27
Usually when that happens it's because the resource isn't available. So in your example it could be that in.close() does not result in the TargetDataLine being closed and released before the next line runs.

**Comment by Cheesemaster64** [comment] 2015-02-10 04:29
Yes, I just wish there was a way to force close all existing lines. Perhaps
it is a driver problem with my laptop's onboard audio card.

I will try using a different computer.

On Tue, Feb 10, 2015 at 1:27 PM, Damien Di Fede <notifications@github.com>
wrote:

> Usually when that happens it's because the resource isn't available. So in
> your example it could be that in.close() does not result in the
> TargetDataLine being closed and released before the next line runs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ddf/Minim/issues/32#issuecomment-73642543>.
>



-- 
Corey Bunnell

**Comment by Cheesemaster64** [comment] 2015-02-10 04:39
I am getting this same error on my other machine.

This machine is also Windows 8 64 bit with java 1.7 and processing 2.21.



On Tue, Feb 10, 2015 at 1:29 PM, master Cheese <cheesemaster64@gmail.com>
wrote:

> Yes, I just wish there was a way to force close all existing lines.
> Perhaps it is a driver problem with my laptop's onboard audio card.
>
> I will try using a different computer.
>
> On Tue, Feb 10, 2015 at 1:27 PM, Damien Di Fede <notifications@github.com>
> wrote:
>
>> Usually when that happens it's because the resource isn't available. So
>> in your example it could be that in.close() does not result in the
>> TargetDataLine being closed and released before the next line runs.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ddf/Minim/issues/32#issuecomment-73642543>.
>>
>
>
>
> --
> Corey Bunnell
>



-- 
Corey Bunnell

**Comment by Cheesemaster64** [comment] 2015-02-10 05:26
I installed eclipse and made a java 1.8 project since I found out the
processing has a local installation of java which it uses.

Still get the same error on both machines.
Hmm.

On Tue, Feb 10, 2015 at 1:39 PM, master Cheese <cheesemaster64@gmail.com>
wrote:

> I am getting this same error on my other machine.
>
> This machine is also Windows 8 64 bit with java 1.7 and processing 2.21.
>
>
>
> On Tue, Feb 10, 2015 at 1:29 PM, master Cheese <cheesemaster64@gmail.com>
> wrote:
>
>> Yes, I just wish there was a way to force close all existing lines.
>> Perhaps it is a driver problem with my laptop's onboard audio card.
>>
>> I will try using a different computer.
>>
>> On Tue, Feb 10, 2015 at 1:27 PM, Damien Di Fede <notifications@github.com
>> > wrote:
>>
>>> Usually when that happens it's because the resource isn't available. So
>>> in your example it could be that in.close() does not result in the
>>> TargetDataLine being closed and released before the next line runs.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ddf/Minim/issues/32#issuecomment-73642543>.
>>>
>>
>>
>>
>> --
>> Corey Bunnell
>>
>
>
>
> --
> Corey Bunnell
>



-- 
Corey Bunnell

**Comment by ddf** [comment] 2015-02-19 01:00
Ok, I can't repro this on my Win7 machine with Processing 2.2.1 or with 3.0a5

If this is a Windows 8 issue I don't have a Win8 machine available to me. :(

**Comment by Cheesemaster64** [comment] 2015-02-19 01:32
Thanks for testing this out.

I got my hands on a windows 7 machine but I got the same error.

Are you using the Java that comes with the processing bundle?

2015年2月19日木曜日、Damien Di Fede<notifications@github.com>さんは書きました:

> Ok, I can't repro this on my Win7 machine with Processing 2.2.1 or with
> 3.0a5
>
> If this is a Windows 8 issue I don't have a Win8 machine available to me.
> :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ddf/Minim/issues/32#issuecomment-74981681>.
>


-- 
Corey Bunnell

**Comment by Cheesemaster64** [comment] 2015-02-19 02:12
Or do you have a nice sound card?

On Thu, Feb 19, 2015 at 10:32 AM, master Cheese <cheesemaster64@gmail.com>
wrote:

> Thanks for testing this out.
>
> I got my hands on a windows 7 machine but I got the same error.
>
> Are you using the Java that comes with the processing bundle?
>
> 2015年2月19日木曜日、Damien Di Fede<notifications@github.com>さんは書きました:
>
>> Ok, I can't repro this on my Win7 machine with Processing 2.2.1 or with
>> 3.0a5
>>
>> If this is a Windows 8 issue I don't have a Win8 machine available to me.
>> :(
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ddf/Minim/issues/32#issuecomment-74981681>.
>>
>
>
> --
> Corey Bunnell
>
>


-- 
Corey Bunnell

**Comment by Cheesemaster64** [comment] 2015-02-19 02:16
Ok, installing the latest minim version fixed my problem.
Not sure what has changed in the last week but the issue is gone now...

I am so confused.

**Comment by ddf** [comment] 2015-02-19 17:27
Ok, glad your problem is resolved but agreed it'd be nice to know why.

I do have a nice external audio interface. If I unplug it so the system falls back to the internal audio card I can't even get an AudioInput in the first place. So that's a thing.

**Closed** 2015-08-30 19:31 UTC
